---
bash_set_errexit: 1
bash_set_pipefail: 1
conda:
  bioconductor-deseq2: 1.22.1=r351hf484d3e_0
  bioconductor-tximport:
  gffcompare: 0.11.2
  numpy:
  pigz:
  pip:
  preseq: 2.0.3=gsl2.2_1
  python: 2.7
  r-optparse:
  r-readr:
  salmon: 0.12.0=h86b0361_1
  scipy:
shell:
  blobfish:
    conda_dependency:
      bioconductor-deseq2:
      bioconductor-tximport:
      python: 2.7
      r-optparse:
      r-readr:
    version: git
    url: https://github.com/J35P312/BlobFish.git
  bootstrapann:
    conda_dependency:
      numpy:
      pip:
      scipy:
    url: https://github.com/J35P312/BootstrapAnn.git
    version: git
  mip_scripts:
    version: Your current MIP version
  gtf2bed:
    version: 1.04.807
    url: https://github.com/ExpressionAnalysis/ea-utils/archive/1.04.807.zip
singularity:
  arriba:
    executable:
      arriba: /arriba_v1.1.0/arriba
      draw_fusions.R: /arriba_v1.1.0/draw_fusions.R
    uri: docker://uhrigs/arriba:1.1.0
  fastqc:
    executable:
      fastqc:
    uri: docker://clinicalgenomics/fastqc:0.11.8
  gatk4:
    executable:
      gatk:
    uri: docker://clinicalgenomics/fastqc:0.11.8
  htslib:
    executable:
      bcftools:
      bgzip:
      samtools:
      tabix:
    uri: docker://clinicalgenomics/htslib:1.9
  multiqc:
    executable:
      multiqc:
    uri: docker://ewels/multiqc:v1.7
  picard:
    executable:
      picard: "no_executable_in_image"
    uri: docker://broadinstitute/picard:2.20.7
  rseqc:
    executable:
      bam2wig.py:
      bam_stat.py:
      geneBody_coverage2.py:
      infer_experiment.py:
      inner_distance.py:
      junction_annotation.py:
      junction_saturation.py:
      read_distribution.py:
      read_duplication.py:
      wigToBigWig:
    uri: library://jemten/mip_containers/rseqc:3.0.1
  sambamba:
    executable:
      sambamba:
    uri: docker://clinicalgenomics/sambamba:0.6.8
  star:
    executable:
      STAR:
    uri: library://jemten/mip_containers/star:2.7.3a
  star-fusion:
    executable:
      blastn:
      gtf_file_to_feature_seqs.pl: /usr/local/src/STAR-Fusion/ctat-genome-lib-builder/util/gtf_file_to_feature_seqs.pl
      make_super_locus.pl: /usr/local/src/STAR-Fusion/ctat-genome-lib-builder/util/make_super_locus.pl
      makeblastdb:
      prep_genome_lib.pl: /usr/local/src/STAR-Fusion/ctat-genome-lib-builder/prep_genome_lib.pl
      remove_long_intron_readthru_transcripts.pl: /usr/local/src/STAR-Fusion/ctat-genome-lib-builder/util/remove_long_intron_readthru_transcripts.pl
      restrict_genome_to_chr_entries.pl: /usr/local/src/STAR-Fusion/ctat-genome-lib-builder/util/restrict_genome_to_chr_entries.pl
      STAR-Fusion: /usr/local/src/STAR-Fusion/STAR-Fusion
    uri: https://github.com/STAR-Fusion/STAR-Fusion/releases/download/v1.8.0/star-fusion.v1.8.0.simg
  stringtie:
    executable:
      stringtie:
    uri: library://jemten/mip_containers/stringtie:2.0.3
  trim-galore:
    executable:
      trim_galore:
    uri: library://jemten/mip_containers/trim-galore:0.6.4
  vep:
    executable:
      vep:
    uri: shub://Clinical-Genomics/MIP:vep-97.4
