---
load_env:
  mip_rd_rna:
    method: conda
    mip:
project_id: development
reference:
  1000g_indels:
    - phase1
  ctat_resource_lib:
    - gencode_v19_ctat_lib_mar012021
    - gencode_v37_ctat_lib_mar012021
  dbsnp:
    - 138_esa_129
    - 138
    - gold_standard_dbsnp
    - 146
  gencode_annotation:
    - v31
    - v34
  human_reference:
    - decoy_5
    - assembly38
    - gencode_pri
  mills_and_1000g_indels:
    - gold_standard_indels
  pfam:
    - 32
reference_feature:
  gencode_annotation:
    grch37:
      v31:
        file: gencode.v31lift37.annotation.gtf.gz
        outfile: grch37_gencode_annotation_-v31-.gtf.gz
        outfile_decompress: gzip
        url_prefix: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_31/GRCh37_mapping/
      v34:
        file: gencode.v34lift37.annotation.gtf.gz
        outfile: grch37_gencode_annotation_-v34-.gtf.gz
        outfile_decompress: gzip
        url_prefix: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_34/GRCh37_mapping/
    grch38:
      v31:
        file: gencode.v31.annotation.gtf.gz
        outfile: grch38_gencode_annotation_-v31-.gtf.gz
        outfile_decompress: gzip
        url_prefix: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_31/
      v34:
        file: gencode.v34.annotation.gtf.gz
        outfile: grch38_gencode_annotation_-v34-.gtf.gz
        outfile_decompress: gzip
        url_prefix: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_34/
  ctat_resource_lib:
    grch37:
      gencode_v19_ctat_lib_mar012021:
        file: GRCh37_gencode_v19_CTAT_lib_Mar012021.plug-n-play.tar.gz
        file_check: GRCh37_gencode_v19_CTAT_lib_Mar012021.plug-n-play.tar.gz.md5sum
        outfile: grch37_gencode_v19_CTAT_lib_Mar012021.plug-n-play.tar.gz
        outfile_check: grch37_gencode_v19_CTAT_lib_Mar012021.plug-n-play.tar.gz.md5
        outfile_decompress: tar
        outfile_check_method: md5sum
        url_prefix: https://data.broadinstitute.org/Trinity/CTAT_RESOURCE_LIB/__genome_libs_StarFv1.10/
    grch38:
      gencode_v37_ctat_lib_mar012021:
        file: GRCh38_gencode_v37_CTAT_lib_Mar012021.plug-n-play.tar.gz
        file_check: GRCh38_gencode_v37_CTAT_lib_Mar012021.plug-n-play.tar.gz.md5sum
        outfile: grch38_gencode_v37_CTAT_lib_Mar012021.plug-n-play.tar.gz
        outfile_check: grch38_gencode_v37_CTAT_lib_Mar012021.plug-n-play.tar.gz.md5
        outfile_decompress: tar
        outfile_check_method: md5sum
        url_prefix: https://data.broadinstitute.org/Trinity/CTAT_RESOURCE_LIB/__genome_libs_StarFv1.10/
  human_reference:
    grch37:
      decoy_5:
        file: human_g1k_v37_decoy.fasta.gz
        file_check: human_g1k_v37_decoy.fasta.gz.md5
        outfile: grch37_homo_sapiens_-d5-.fasta.gz
        outfile_check: grch37_homo_sapiens_-d5-.fasta.gz.md5
        url_prefix: https://storage.googleapis.com/gatk-legacy-bundles/b37/
        outfile_decompress: gzip
        outfile_check_method: md5sum
      gencode_pri:
        file: GRCh37.primary_assembly.genome.fa.gz
        outfile: grch37_homo_sapiens_-gencode_pri-.fasta.gz
        url_prefix: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_37/GRCh37_mapping/
        outfile_decompress: gzip
    grch38:
      assembly38:
        file: Homo_sapiens_assembly38.fasta
        outfile: grch38_homo_sapiens_-assembly-.fasta
        url_prefix: https://storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/
      gencode_pri:
        file: GRCh38.primary_assembly.genome.fa.gz
        outfile: grch38_homo_sapiens_-gencode_pri-.fasta.gz
        url_prefix: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_37/
        outfile_decompress: gzip
  1000g_indels:
    grch37:
      phase1:
        file: 1000G_phase1.indels.b37.vcf.gz
        file_check: 1000G_phase1.indels.b37.vcf.gz.md5
        file_index: 1000G_phase1.indels.b37.vcf.idx.gz
        file_index_check: 1000G_phase1.indels.b37.vcf.idx.gz.md5
        outfile: grch37_1000g_indels_-phase1-.vcf.gz
        outfile_check: grch37_1000g_indels_-phase1-.vcf.gz.md5
        outfile_index: grch37_1000g_indels_-phase1-.vcf.idx.gz
        outfile_index_check: grch37_1000g_indels_-phase1-.vcf.idx.gz.md5
        outfile_decompress: gzip
        outfile_index_decompress: gzip
        outfile_check_method: md5sum
        outfile_index_check_method: md5sum
        url_prefix: https://storage.googleapis.com/gatk-legacy-bundles/b37/
    grch38:
      phase1:
        file: Homo_sapiens_assembly38.known_indels.vcf.gz
        file_index: Homo_sapiens_assembly38.known_indels.vcf.gz.tbi
        outfile: grch38_1000g_indels_-phase1-.vcf.gz
        outfile_index: grch38_1000g_indels-phase1-.vcf.gz.tbi
        url_prefix: https://storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/
  mills_and_1000g_indels:
    grch37:
      gold_standard_indels:
        file: Mills_and_1000G_gold_standard.indels.b37.vcf.gz
        file_check: Mills_and_1000G_gold_standard.indels.b37.vcf.gz.md5
        file_index: Mills_and_1000G_gold_standard.indels.b37.vcf.idx.gz
        file_index_check: Mills_and_1000G_gold_standard.indels.b37.vcf.idx.gz.md5
        outfile: grch37_mills_and_1000g_-gold_standard_indels-.vcf.gz
        outfile_check: grch37_mills_and_1000g_-gold_standard_indels-.vcf.gz.md5
        outfile_index: grch37_mills_and_1000g_-gold_standard_indels-.vcf.idx.gz
        outfile_index_check: grch37_mills_and_1000g_-gold_standard_indels-.vcf.idx.gz.md5
        outfile_decompress: gzip
        outfile_index_decompress: gzip
        outfile_check_method: md5sum
        outfile_index_check_method: md5sum
        url_prefix: https://storage.googleapis.com/gatk-legacy-bundles/b37/
    grch38:
      gold_standard_indels:
        file: Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
        file_index: Mills_and_1000G_gold_standard.indels.hg38.vcf.gz.tbi
        outfile: grch38_mills_and_1000g_-gold_standard_indels-.vcf.gz
        outfile_index: grch38_mills_and_1000g_-gold_standard_indels-.vcf.gz.tbi
        url_prefix: https://storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/
  dbsnp:
    grch37:
      138_esa_129:
        file: dbsnp_138.b37.excluding_sites_after_129.vcf.gz
        file_check: dbsnp_138.b37.excluding_sites_after_129.vcf.gz.md5
        file_index: dbsnp_138.b37.excluding_sites_after_129.vcf.idx.gz
        file_index_check: dbsnp_138.b37.excluding_sites_after_129.vcf.idx.gz.md5
        outfile: grch37_dbsnp_-138_esa_129-.vcf.gz
        outfile_check: grch37_dbsnp_-138_esa_129-.vcf.gz.md5
        outfile_index: grch37_dbsnp_-138_esa_129-.vcf.idx.gz
        outfile_index_check: grch37_dbsnp_-138_esa_129-.vcf.idx.gz.md5
        outfile_decompress: gzip
        outfile_index_decompress: gzip
        outfile_check_method: md5sum
        outfile_index_check_method: md5sum
        url_prefix: https://storage.googleapis.com/gatk-legacy-bundles/b37/
      138:
        file: dbsnp_138.b37.vcf.gz
        file_check: dbsnp_138.b37.vcf.gz.md5
        file_index: dbsnp_138.b37.vcf.idx.gz
        file_index_check: dbsnp_138.b37.vcf.idx.gz.md5
        outfile: grch37_dbsnp_-138-.vcf.gz
        outfile_check: grch37_dbsnp_-138-.vcf.gz.md5
        outfile_index: grch37_dbsnp_-138-.vcf.idx.gz
        outfile_index_check: grch37_dbsnp_-138-.vcf.idx.gz.md5
        outfile_decompress: gzip
        outfile_index_decompress: gzip
        outfile_check_method: md5sum
        outfile_index_check_method: md5sum
        url_prefix: https://storage.googleapis.com/gatk-legacy-bundles/b37/
    grch38:
      gold_standard_dbsnp:
        file: Homo_sapiens_assembly38.variantEvalGoldStandard.vcf.gz
        file_index: Homo_sapiens_assembly38.variantEvalGoldStandard.vcf.gz.tbi
        outfile: grch38_variant_-gold_standard_dbsnp-.vcf.gz
        outfile_decompress: gzip
        outfile_index: grch38_variant_-gold_standard_dbsnp-.vcf.gz.tbi
        url_prefix: ftp://gsapubftp-anonymous@ftp.broadinstitute.org/bundle/hg38/beta/
        user: gsapubftp-anonymous
      146:
        file: dbsnp_146.hg38.vcf.gz
        file_index: dbsnp_146.hg38.vcf.gz.tbi
        outfile: grch38_dbsnp_-146-.vcf.gz
        outfile_decompress: gzip
        outfile_index: grch38_dbsnp_-146-.vcf.gz.tbi
        url_prefix: ftp://gsapubftp-anonymous@ftp.broadinstitute.org/bundle//hg38/
        user: gsapubftp-anonymous
  pfam:
    grch37:
      32:
        file: Pfam-A.hmm.gz
        outfile: pfam_a_-v32-.hmm.gz
        outfile_decompress: gzip
        url_prefix: ftp://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam32.0/
    grch38:
      32:
        file: Pfam-A.hmm.gz
        outfile: pfam_a_-v32-.hmm.gz
        outfile_decompress: gzip
        url_prefix: ftp://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam32.0/
