---
# MIP main environment spec
emip:
  conda:
    bcftools: 1.9=ha228f0b_4
    bioconductor-deseq2: 1.22.1=r351hf484d3e_0
    bioconductor-tximport:
    gatk4: 4.1.0.0=0
    gffcompare: 0.10.6=h2d50403_0
    htslib: 1.9=hc238db4_4
    numpy:
    picard: 2.18.23=0
    pigz:
    pip:
    preseq: 2.0.3=gsl2.2_1
    python: 2.7
    r-optparse:
    r-readr:
    salmon: 0.12.0=h86b0361_1
    sambamba: 0.6.8=h682856c_1
    samtools: 1.9=h8571acd_11
    scipy:
    stringtie: 1.3.4=py27_0
  shell:
    blobfish:
      conda_dependency:
        bioconductor-deseq2:
        bioconductor-tximport:
        python: 2.7
        r-optparse:
        r-readr:
      version: git
      url: https://github.com/J35P312/BlobFish.git
    bootstrapann:
      conda_dependency:
        numpy:
        pip:
        scipy:
      url: https://github.com/J35P312/BootstrapAnn.git
      version: git
    mip_scripts:
      version: Your current MIP version
    picard:
      version: 2.17.11
    gtf2bed:
      version: 1.04.807
      url: https://github.com/ExpressionAnalysis/ea-utils/archive/1.04.807.zip
## Python 3 environment spec
epy3:
  conda:
    bedops: 2.4.35=h2d50403_1
    pip:
    python: 3.6
    ucsc-wigtobigwig: 366=hdd26221_0
  pip:
    multiqc: 1.6
    rseqc: 3.0.0
  shell:
## STAR environment spec
eperl5:
  conda:
    blast: 2.7.1=h4422958_6
    fastqc: 0.11.8=1
    fusion-filter: 0.5.0
    perl-common-sense:
    perl-json-xs:
    perl-db-file:
    star-fusion: 1.5.0=0
    star: 2.6.1d=0
    trim-galore: 0.5.0
  pip:
  shell:
# VEP environment spec
evep:
  conda:
    bcftools: 1.9=ha228f0b_4
    htslib: 1.9=hc238db4_4
    pip:
    python: 2.7
    tabix: 0.2.6
  pip:
  shell:
    vep:
      conda_dependency:
        bcftools:
        htslib:
        tabix:
      vep_assemblies:
        - GRCh37
        - GRCh38
      vep_auto_flag: acf
      vep_cache_dir: ~
      vep_plugins:
        -
      vep_species:
        - homo_sapiens_merged
      version: 95
## Default base name
environment_base_name: mip7_rd-rna
# Specify environment names
environment_name:
  emip: mip7_rd-rna
  epy3: mip7_rd-rna_py3
  eperl5: mip7_rd-rna_perl5
  evep: mip7_rd-rna_vep
## Test that the program is executable and has been added to PATH
program_test_command:
  bcftools:
    execution: 'bcftools --version'
    path: 'bcftools'
  bedops:
    execution: 'bedops --version'
    path: 'bedops'
  bioconductor-deseq2:
    execution: 'R -e "library(DESeq2)"'
    path:
  bioconductor-tximport:
    execution: 'R -e "library(tximport)"'
    path:
  blast:
    execution: 'blastn -version'
    path: 'blastn'
  blobfish:
    execution: 'BlobFish.py'
    path: 'BlobFish.py'
  bootstrapann:
    execution: 'BootstrapAnn.py --help'
    path: 'BootstrapAnn.py'
  fastqc:
    execution: 'fastqc --version'
    path: 'fastqc'
  fusion-filter:
    execution:
    path: 'gtf_file_to_feature_seqs.pl'
  gatk4:
    execution: 'gatk'
    path: 'gatk'
  gffcompare:
    execution: 'gffcompare --version'
    path: 'gffcompare'
  htslib:
    execution: 'bgzip --version'
    path: 'bgzip'
  mip_scripts:
    execution: 'mip --help'
    path: 'mip'
  multiqc:
    execution: 'multiqc --version'
    path: 'multiqc'
  numpy:
    execution: 'python -c "import numpy"'
    path:
  picard:
    execution:
    path: 'picard'
  preseq:
    execution: 'preseq'
    path: 'preseq'
  r-optparse:
    execution: 'R -e "library(tximport)"'
    path:
  r-readr:
    execution: 'R -e "library(readr)"'
    path:
  rseqc:
    execution: 'inner_distance.py'
    path: 'inner_distance.py'
  salmon:
    execution: 'salmon --version'
    path: 'salmon'
  sambamba:
    execution: 'sambamba --version'
    path: 'sambamba'
  samtools:
    execution: 'samtools --version'
    path: 'samtools'
  scipy:
    execution: 'python -c "import scipy"'
    path:
  star-fusion:
    execution: 'STAR-Fusion --version'
    path: 'STAR-Fusion'
  star:
    execution: 'STAR'
    path: 'STAR'
  stringtie:
    execution: 'stringtie --version'
    path: 'stringtie'
  ucsc-wigtobigwig:
    path: 'wigToBigWig'
  vep:
    execution: 'vep'
    path: 'vep'

# Programs that needs to be installed with pyhton 3,
# only touch if you know what you're doing
python3_programs: []

# Supress output, both when generating the install script and running it
quiet: 0

# Path to directory to which reference genomes are to be downloaded
reference_dir: ~

# Reference genomes to download
reference_genome_versions:
  - grch37
  - hg38

## Sbath options
core_number: 1
email:
email_types:
  - FAIL
process_time: 2-00:00:00
project_id:
sbatch_mode: 0
slurm_quality_of_service: low

# Select programs to install, skip the rest
select_programs: []

# Select programs that are to be installed via shell instead of conda
shell_install: []

# Don't write installation instructions for these programs
skip_programs: []

# Path to existing config to update
update_config: ~

# Verbose output when running the generated install script
verbose: 0

# Write config based on template
write_config: ~
